### PR TITLE
New WEBSITE UI DESIGN

### PR DESCRIPTION
**Pull request by abitsalihu**
I have changed the UI to something more stylish and minimalistic, the design is also dynamic. That means the background photo will change based on what the time of the user is at that particular moment. You can see the design below!

This is how the website will look like when the time at the user is between 6am and 12pm:

Screen Shot 2022-09-07 at 12 41 59

This is how the website will look like when the time at the user is between 13pm and 15pm:

Screen Shot 2022-09-07 at 12 42 07

This is how the website will look like when the time at the user is between 16pm and 19pm:

Screen Shot 2022-09-07 at 12 42 14

This is how the website will look like when the time at the user is between 20pm and 5am:

Screen Shot 2022-09-07 at 12 42 21

### CODE REVIEW

**Comment by DanCQ** [comment]
Wow. Impressive!

**Comment by abitsalihu** [comment]
Glad I could help 🙂

**Comment by DanCQ** [comment]
It's better than my Amazon Show display. I'm going to keep an enhancement issue on it. 
The only way I could see it enhanced though, is with animated backgrounds, or with a further addition of themes. 

As it is I can picture people using it on tv displays in public spaces. As an artistic time display.

**Comment by abitsalihu** [comment]
Yeah that's pretty smart, someone can make a folder of morning pictures and have those slideshow automatically during certain hours and then do the same thing for afternoon and evening!

**Comment by DanCQ** [comment]
This is the [enhancement issue](https://github.com/DanCQ/Digital-Clock--Javascript/issues/4#issue-1364978491) link.

I'm not going to suggest how to enhance it, 
since others' ideas might be more interesting than I expected.

It's pretty amazing as it is now. 
We'll see what happens.

**Pull request merged**
